### ISSUE TITLE
Реализация бара прогресса

### ISSUE THREAD

**Issue by MenacingDwarf** [MenacingDwarf/CITEC-Website#27]
Реализовать бар прогресса, основываясь на прогрессе milestones, то есть перевод открытых и закрытых issues во всех milestones в одно число: от 0 до 100. Грубо говоря мы должны взять все milestones проекта, посчитать прогресс в процентах по каждому из них, сложить проценты и поделить на количество проектов

**Comment by skurdenis** [comment]
https://github.com/skurdenis/fcdhjgrdjd/blob/master/samplequery
Вроде более или менее работает этот запрос
