### ISSUE TITLE
Реализация бара прогресса

### ISSUE THREAD

**Issue by MenacingDwarf** [MenacingDwarf/CITEC-Website#35]
### Описание проблемы
При получении списка проектов помимо различной информации о проекте необходимо, чтобы у каждого проекта отображался его прогресс в виде прогресбара с процентами.
### Что нужно сделать
Реализовать и вставить в проект бар прогресса на основе схемы и запроса #27 
### Дэдлайн
02.12.2018 23:59

**Comment by voismager** [comment]
В README в ближайшее время напишу как всё в общем устроено
