### ISSUE TITLE
Реализация получения проектов

### ISSUE THREAD

**Issue by MenacingDwarf** [MenacingDwarf/CITEC-Website#47]
Реализация придуманного в  #46 способа получения проектов

**Comment by voismager** [comment]
Можно подробности придуманного способа?

**Comment by MenacingDwarf** [comment]
Способ ещё не был придуман, надо организовывать встречу

**Comment by MenacingDwarf** [comment]
@gRastaSsS Было решено обойтись без получения, подробнее в #46
