### ISSUE TITLE
График

### ISSUE THREAD

**Issue by MenacingDwarf** [MenacingDwarf/CITEC-Website#57]
### Описание проблемы
На странице с подробным описание проекта есть график, который сейчас не наполнен информацией, полученной с back-end.
### Что нужно сделать
Написать правильный запрос для получения необходимых данных с сервера и правильно отобразить их на графике. Необходимые данные - это количество закрытых ишьюс по дням, начиная с начала работы над проектом и заканчивая нынешней датой
### Дэдлайн
07.12.2018 14:30

**Comment by avdeev1** [comment]
Добавлен график, с возможностью регулирования (в скрипте запроса) интервалов времени, в которых берутся значения
